language: go

go:
 - tip

addons:
    postgresql: "10"
    apt:
      packages:
        - postgresql-10-postgis-2.4
        - libgeos-dev
        - libprotobuf-dev
        - protobuf-compiler
        - osmosis

before_script:
  - sudo /etc/init.d/postgresql stop
  - psql -U postgres -c 'create database travis' || true
  - psql -U postgres -c "create extension if not exists postgis"
  - psql -U postgres -c "create extension if not exists hstore"

env:
  global:
    - PGUSER=postgres

install:
  - LEVELDB_VER=1.20
  - curl -fsSL https://github.com/google/leveldb/archive/v${LEVELDB_VER}.tar.gz | tar -C ${HOME} -xzf -
  - make -C ${HOME}/leveldb-${LEVELDB_VER} -j2
  - sudo mv ${HOME}/leveldb-${LEVELDB_VER}/out-static/libleveldb* /usr/lib
  - sudo mv ${HOME}/leveldb-${LEVELDB_VER}/out-shared/libleveldb* /usr/lib
  - sudo cp -a ${HOME}/leveldb-${LEVELDB_VER}/include/leveldb /usr/include

script: make
